
DISCORD_API_TOKEN ='Your Discord API token here' # PLACE YOUR TOKEN
EXCEL_SHEET_PATH = r'C:\\Users\\file\\path\\here\\filename.xlsx' # DEFINE THE PATH WHERE YOUR SHEET IS LOCATED
SERVER_NAME = "juan pablo's server" 
ROLE_NAME = 'internsummer' # YOU MAY HAVE TO CHANGE THIS ACCORDINGLY
ROW_NAME = 'Your name' # YOU MAY HAVE TO CHANGE THIS ACCORDINGLY




